name: build gatsby

on:
  push:
    branches:
      - gh-pages

jobs:
  build_gatsby:
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: yarn install
        run: yarn install

      - name: gatsby build
        env:
          GH_API_KEY: ${{ secrets.GITHUB }}
        run: yarn build

      - name: deploy
        uses: maxheld83/ghpages@v0.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_AUTOMATION_TOKEN }}
          GH_PAT: ${{ secrets.DEPLOY_AUTOMATION }}
          BUILD_DIR: 'public/'
